// middleware.ts
import { NextResponse, type NextRequest } from "next/server";
import { createServerClient } from "@supabase/ssr";

/**
 * Files + routes that should NEVER be auth-guarded.
 * (Avoids local dev PWA/manifest issues + lets Next serve public assets normally.)
 */
const PUBLIC_PATHS = new Set([
  "/", // login
  "/signup",
  "/forgot",
  "/reset",
  "/auth/callback",

  // common static assets
  "/favicon.ico",
  "/apple-touch-icon.png",
  "/anchorp.svg",

  // PWA
  "/manifest.webmanifest",
  "/manifest.json",
  "/sw.js",
]);

function isPublicAssetPath(pathname: string) {
  // Next internals + static
  if (pathname.startsWith("/_next")) return true;
  if (pathname.startsWith("/static")) return true;

  // PWA / workbox files generated by next-pwa
  if (pathname.startsWith("/workbox-")) return true;
  if (pathname.startsWith("/worker-")) return true;

  // Common asset extensions from /public
  if (/\.(?:png|jpg|jpeg|gif|webp|svg|ico|css|js|map|txt|xml|json|webmanifest)$/i.test(pathname)) {
    return true;
  }

  return false;
}

function isPublicPath(pathname: string) {
  if (PUBLIC_PATHS.has(pathname)) return true;
  if (isPublicAssetPath(pathname)) return true;
  return false;
}

export async function middleware(req: NextRequest) {
  const { pathname } = req.nextUrl;

  // ✅ Public routes/assets pass through
  if (isPublicPath(pathname)) return NextResponse.next();

  // ✅ Create response so Supabase can refresh cookies
  const res = NextResponse.next();

  const supabase = createServerClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
    {
      cookies: {
        getAll() {
          return req.cookies.getAll();
        },
        setAll(cookiesToSet) {
          cookiesToSet.forEach(({ name, value, options }) => {
            res.cookies.set(name, value, options);
          });
        },
      },
    }
  );

  // ✅ Validate session
  const { data } = await supabase.auth.getUser();
  const user = data.user;

  if (!user) {
    const loginUrl = req.nextUrl.clone();
    loginUrl.pathname = "/";
    loginUrl.searchParams.set("next", pathname);
    return NextResponse.redirect(loginUrl);
  }

  return res;
}

/**
 * Keep matchers tight:
 * - Protect /chat UI
 * - Protect /api/chat and /api/docs (since those require auth)
 * - Do NOT match /manifest.webmanifest or other public assets
 */
export const config = {
  matcher: ["/chat/:path*", "/api/chat/:path*", "/api/docs/:path*"],
};
